/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import javax.swing.*;

/**
 *
 * @author pedro.5973
 */
public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPanePrincipal = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuContato = new javax.swing.JMenu();
        jMenuItemCadastrarContato = new javax.swing.JMenuItem();
        jMenuItemListarContato = new javax.swing.JMenuItem();
        jMenuEndereco = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(jTabbedPanePrincipal, java.awt.BorderLayout.CENTER);

        jMenuContato.setText("Contato");

        jMenuItemCadastrarContato.setText("Cadastrar");
        jMenuItemCadastrarContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarContatoActionPerformed(evt);
            }
        });
        jMenuContato.add(jMenuItemCadastrarContato);

        jMenuItemListarContato.setText("Listar");
        jMenuItemListarContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarContatoActionPerformed(evt);
            }
        });
        jMenuContato.add(jMenuItemListarContato);

        jMenuBar1.add(jMenuContato);

        jMenuEndereco.setText("Endereco");
        jMenuEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEnderecoActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuEndereco);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadastrarContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarContatoActionPerformed
        // TODO add your handling code here:
        String tabTitle = "Cadastrar Contato";
        boolean tabExists = false;

        // Verifica se a aba já existe
        for (int i = 0; i < jTabbedPanePrincipal.getTabCount(); i++) {
            if (jTabbedPanePrincipal.getTitleAt(i).equals(tabTitle)) {
                tabExists = true;
                break;
            }
        }

        // Se a aba não existir, adiciona uma nova aba
        if (!tabExists) {
            PanelCadastrarContato panelContato = new PanelCadastrarContato();
            jTabbedPanePrincipal.addTab(tabTitle, panelContato);
        }
    }//GEN-LAST:event_jMenuItemCadastrarContatoActionPerformed

    private void jMenuEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuEnderecoActionPerformed

    private void jMenuItemListarContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarContatoActionPerformed
        // TODO add your handling code here:
        String tabTitle = "Listar Contato";
        boolean tabExists = false;

        for (int i = 0; i < jTabbedPanePrincipal.getTabCount(); i++) {
            if (jTabbedPanePrincipal.getTitleAt(i).equals(tabTitle)) {
                tabExists = true;
                break;
            }
        }

        if (!tabExists) {
            PanelListarContato panelListarContato = new PanelListarContato();
            jTabbedPanePrincipal.addTab(tabTitle, panelListarContato);
        }
    }//GEN-LAST:event_jMenuItemListarContatoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuContato;
    private javax.swing.JMenu jMenuEndereco;
    private javax.swing.JMenuItem jMenuItemCadastrarContato;
    private javax.swing.JMenuItem jMenuItemListarContato;
    private javax.swing.JTabbedPane jTabbedPanePrincipal;
    // End of variables declaration//GEN-END:variables
}
