package visao;

import modelo.ContatosTableModel;
import controle.EnderecoControle;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.TableCellRenderer;
import modelo.Endereco;

/**
 *
 * @author pedro.5973
 */
public class PanelListarContato extends javax.swing.JPanel {

    private ContatosTableModel tableModel = new ContatosTableModel(new ArrayList<>());

    /**
     * Creates new form PanelListarContato
     */
    public PanelListarContato() {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneContatos = new javax.swing.JScrollPane();
        jTableListagemContatos = new javax.swing.JTable(tableModel) {
            @Override
            public Component prepareRenderer(TableCellRenderer renderer, int row, int column) {
                Component component = super.prepareRenderer(renderer, row, column);
                if (column == 10) {
                    JButton button = new JButton("Gerenciar");
                    button.addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e) {
                            Endereco endereco = tableModel.getEnderecos().get(row);
                            abrirJanelaGerenciar(endereco);
                        }
                    });
                    return button;
                }
                return component;
            }
        };
        jLfiltros = new javax.swing.JLabel();
        jLnome = new javax.swing.JLabel();
        jTFnome = new javax.swing.JTextField();
        jLtelefone = new javax.swing.JLabel();
        jTFtelefone = new javax.swing.JTextField();
        jLcelular = new javax.swing.JLabel();
        jTFcelular = new javax.swing.JTextField();
        jLemail = new javax.swing.JLabel();
        jTFemail = new javax.swing.JTextField();
        jLestado = new javax.swing.JLabel();
        jTFestado = new javax.swing.JTextField();
        jLcidade = new javax.swing.JLabel();
        jTFcidade = new javax.swing.JTextField();
        jBlimpar = new javax.swing.JButton();
        jBfiltrar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        jScrollPaneContatos.setViewportView(jTableListagemContatos);
        carregarEnderecos(null, null, null, null, null, null);

        jLfiltros.setText("Filtros:");

        jLnome.setText("Nome");

        jTFnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFnomeActionPerformed(evt);
            }
        });

        jLtelefone.setText("Telefone");

        jTFtelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFtelefoneActionPerformed(evt);
            }
        });

        jLcelular.setText("Celular");

        jTFcelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFcelularActionPerformed(evt);
            }
        });

        jLemail.setText("E-Mail");

        jTFemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFemailActionPerformed(evt);
            }
        });

        jLestado.setText("Estado");

        jTFestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFestadoActionPerformed(evt);
            }
        });

        jLcidade.setText("Cidade");

        jTFcidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFcidadeActionPerformed(evt);
            }
        });

        jBlimpar.setText("Limpar");
        jBlimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlimparActionPerformed(evt);
            }
        });

        jBfiltrar.setText("Filtrar");
        jBfiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBfiltrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPaneContatos, javax.swing.GroupLayout.DEFAULT_SIZE, 937, Short.MAX_VALUE)
                        .addGap(54, 54, 54))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLcelular)
                            .addComponent(jLnome)
                            .addComponent(jLfiltros))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFnome, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFcelular, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLtelefone)
                            .addComponent(jLemail))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFtelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFemail, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLcidade)
                            .addComponent(jLestado))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFestado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFcidade, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(140, 140, 140)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBlimpar)
                            .addComponent(jBfiltrar))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLfiltros)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLnome)
                    .addComponent(jTFnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLtelefone)
                    .addComponent(jTFtelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLestado)
                    .addComponent(jTFestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBlimpar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLcelular)
                    .addComponent(jLemail)
                    .addComponent(jTFemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFcelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLcidade)
                    .addComponent(jTFcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBfiltrar))
                .addGap(27, 27, 27)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneContatos, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTFnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFnomeActionPerformed

    private void jTFtelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFtelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFtelefoneActionPerformed

    private void jTFcelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFcelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFcelularActionPerformed

    private void jTFemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFemailActionPerformed

    private void jTFestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFestadoActionPerformed

    private void jTFcidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFcidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFcidadeActionPerformed

    private void jBlimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlimparActionPerformed
        // TODO add your handling code here:
        limpar();
    }//GEN-LAST:event_jBlimparActionPerformed

    private void jBfiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBfiltrarActionPerformed
        // TODO add your handling code here:
        filtrar();
    }//GEN-LAST:event_jBfiltrarActionPerformed

    private void carregarEnderecos(String nome, String telefone, String celular, String email, String estado, String cidade) {

        try {
            EnderecoControle enderecoControle = new EnderecoControle();
            List<Endereco> enderecos = enderecoControle.listarFiltrado(nome, telefone, celular, email, estado, cidade);

            tableModel = new ContatosTableModel(enderecos);
            jTableListagemContatos.setModel(tableModel);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar endereços: " + e.getMessage());
        }
    }

    public void filtrar() {
        String nome = jTFnome.getText();
        String telefone = jTFtelefone.getText();
        String celular = jTFcelular.getText();
        String email = jTFemail.getText();
        String estado = jTFestado.getText();
        String cidade = jTFcidade.getText();

        carregarEnderecos(nome, telefone, celular, email, estado, cidade);
    }

    private void limpar() {
        jTFnome.setText("");
        jTFtelefone.setText("");
        jTFcelular.setText("");
        jTFemail.setText("");
        jTFestado.setText("");
        jTFcidade.setText("");

        carregarEnderecos(null, null, null, null, null, null);
    }

    private void abrirJanelaGerenciar(Endereco endereco) {
        JFrame frame = new JFrame("Gerenciar Contato");
        frame.setSize(400, 300);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setLayout(new BorderLayout());

        JPanel panel = new JPanel(new GridLayout(6, 2));
        JTextField nomeField = new JTextField(endereco.getContato().getNome());
        JTextField telefoneField = new JTextField(endereco.getContato().getTelefone());
        JTextField celularField = new JTextField(endereco.getContato().getCelular());
        JTextField emailField = new JTextField(endereco.getContato().getEmail());
        JTextField ruaField = new JTextField(endereco.getRua());
        JTextField numeroField = new JTextField(endereco.getNumero());

        panel.add(new JLabel("Nome:"));
        panel.add(nomeField);
        panel.add(new JLabel("Telefone:"));
        panel.add(telefoneField);
        panel.add(new JLabel("Celular:"));
        panel.add(celularField);
        panel.add(new JLabel("Email:"));
        panel.add(emailField);
        panel.add(new JLabel("Rua:"));
        panel.add(ruaField);
        panel.add(new JLabel("Número:"));
        panel.add(numeroField);

        frame.add(panel, BorderLayout.CENTER);

        JPanel buttonPanel = new JPanel();
        JButton saveButton = new JButton("Salvar");
        saveButton.addActionListener(e -> {
                endereco.getContato().setNome(nomeField.getText());
                endereco.getContato().setTelefone(telefoneField.getText());
                endereco.getContato().setCelular(celularField.getText());
                endereco.getContato().setEmail(emailField.getText());
                endereco.setRua(ruaField.getText());
                endereco.setNumero(numeroField.getText());

                EnderecoControle enderecoControle = new EnderecoControle();
                enderecoControle.alterar(endereco);

                JOptionPane.showMessageDialog(frame, "Contato atualizado com sucesso!");
                frame.dispose();
                carregarEnderecos(null, null, null, null, null, null); // Recarregar a tabela
        });

        JButton deleteButton = new JButton("Excluir");
        deleteButton.addActionListener(e -> {
            int confirm = JOptionPane.showConfirmDialog(frame, "Tem certeza de que deseja excluir este contato?", "Confirmar Exclusão", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                    EnderecoControle enderecoControle = new EnderecoControle();
                    enderecoControle.delete(endereco.getId());

                    JOptionPane.showMessageDialog(frame, "Contato excluído com sucesso!");
                    frame.dispose();
                    carregarEnderecos(null, null, null, null, null, null); // Recarregar a tabela
            }
        });

        buttonPanel.add(saveButton);
        buttonPanel.add(deleteButton);
        frame.add(buttonPanel, BorderLayout.SOUTH);

        frame.setVisible(true);
    }
    
//    public void editarContato(int row) {
//        Endereco endereco = tableModel.getEndereco(row);
//        PanelEditarContato editarContato = new PanelEditarContato(endereco);
//        JTabbedPane tabbedPane = (JTabbedPane) SwingUtilities.getAncestorOfClass(JTabbedPane.class, this);
//        tabbedPane.addTab("Editar Contato", editarContato);
//        tabbedPane.setSelectedComponent(editarContato);
//    }
//
//    public void excluirContato(int row) {
//        int confirm = JOptionPane.showConfirmDialog(this, "Tem certeza de que deseja excluir este contato?", "Confirmação", JOptionPane.YES_NO_OPTION);
//        if (confirm == JOptionPane.YES_OPTION) {
//            Endereco endereco = tableModel.getEndereco(row);
//            EnderecoControle enderecoControle = new EnderecoControle();
//            enderecoControle.delete(endereco.getId());
//            carregarEnderecos(null, null, null, null, null, null);
//
//        }
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBfiltrar;
    private javax.swing.JButton jBlimpar;
    private javax.swing.JLabel jLcelular;
    private javax.swing.JLabel jLcidade;
    private javax.swing.JLabel jLemail;
    private javax.swing.JLabel jLestado;
    private javax.swing.JLabel jLfiltros;
    private javax.swing.JLabel jLnome;
    private javax.swing.JLabel jLtelefone;
    private javax.swing.JScrollPane jScrollPaneContatos;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTFcelular;
    private javax.swing.JTextField jTFcidade;
    private javax.swing.JTextField jTFemail;
    private javax.swing.JTextField jTFestado;
    private javax.swing.JTextField jTFnome;
    private javax.swing.JTextField jTFtelefone;
    private javax.swing.JTable jTableListagemContatos;
    // End of variables declaration//GEN-END:variables
}
