package visao;

import modelo.Endereco;

/**
 *
 * @author pedro.5973
 */
public class PanelEditarContato extends javax.swing.JPanel {
    private Endereco endereco;
    /**
     * Creates new form PanelContato
     * @param endereco
     */
    public PanelEditarContato(Endereco endereco) {
        initComponents();
        this.endereco = endereco;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLnome = new javax.swing.JLabel();
        jLtelefone = new javax.swing.JLabel();
        jLcelular = new javax.swing.JLabel();
        jLemail = new javax.swing.JLabel();
        jTFtelefone = new javax.swing.JTextField(15);
        jTFnome = new javax.swing.JTextField(endereco.getContato().getNome());
        jTFemail = new javax.swing.JTextField(30);
        jTFcelular = new javax.swing.JTextField(15);
        jLrua = new javax.swing.JLabel();
        jTFrua = new javax.swing.JTextField(30);
        jLnumero = new javax.swing.JLabel();
        jTFnumero = new javax.swing.JTextField(4);
        jLestado = new javax.swing.JLabel();
        jLuf = new javax.swing.JLabel();
        jTFestado = new javax.swing.JTextField(30);
        jTFuf = new javax.swing.JTextField(2);
        jLcidade = new javax.swing.JLabel();
        jTFcidade = new javax.swing.JTextField(30);
        jBsalvar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLnome.setText("Nome");
        add(jLnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        jLtelefone.setText("Telefone");
        add(jLtelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));

        jLcelular.setText("Celular");
        add(jLcelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        jLemail.setText("Email");
        add(jLemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));
        add(jTFtelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 90, -1));
        add(jTFnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 90, -1));
        add(jTFemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 90, -1));
        add(jTFcelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 90, -1));

        jLrua.setText("Rua");
        add(jLrua, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));
        add(jTFrua, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 90, -1));

        jLnumero.setText("Número");
        add(jLnumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, -1));
        add(jTFnumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 90, -1));

        jLestado.setText("Estado");
        add(jLestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        jLuf.setText("UF");
        add(jLuf, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));
        add(jTFestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 90, -1));
        add(jTFuf, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 90, -1));

        jLcidade.setText("Cidade");
        add(jLcidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));
        add(jTFcidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 90, -1));

        jBsalvar.setText("Salvar");
        jBsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalvarActionPerformed(evt);
            }
        });
        add(jBsalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jBsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalvarActionPerformed
        // TODO add your handling code here:
        endereco.getContato().setNome(jTFnome.getText());
        endereco.getContato().setTelefone(jTFtelefone.getText());
        endereco.getContato().setCelular(jTFcelular.getText());
        endereco.getContato().setEmail(jTFemail.getText());
        endereco.setRua(jTFrua.getText());
        endereco.setNumero(jTFnumero.getText());
        endereco.getCidade().setEstado(jTFestado.getText());
        endereco.getCidade().setUf(jTFuf.getText());
        endereco.getCidade().setNome(jTFcidade.getText());
    }//GEN-LAST:event_jBsalvarActionPerformed

    private void populateFields() {
        jTFnome.setText(endereco.getContato().getNome());
        jTFtelefone.setText(endereco.getContato().getTelefone());
        jTFcelular.setText(endereco.getContato().getCelular());
        jTFemail.setText(endereco.getContato().getEmail());
        jTFrua.setText(endereco.getRua());
        jTFnumero.setText(endereco.getNumero());
        jTFestado.setText(endereco.getCidade().getEstado());
        jTFuf.setText(endereco.getCidade().getUf());
        jTFcidade.setText(endereco.getCidade().getNome());
    }

    public Endereco getEndereco() {
        return endereco;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBsalvar;
    private javax.swing.JLabel jLcelular;
    private javax.swing.JLabel jLcidade;
    private javax.swing.JLabel jLemail;
    private javax.swing.JLabel jLestado;
    private javax.swing.JLabel jLnome;
    private javax.swing.JLabel jLnumero;
    private javax.swing.JLabel jLrua;
    private javax.swing.JLabel jLtelefone;
    private javax.swing.JLabel jLuf;
    private javax.swing.JTextField jTFcelular;
    private javax.swing.JTextField jTFcidade;
    private javax.swing.JTextField jTFemail;
    private javax.swing.JTextField jTFestado;
    private javax.swing.JTextField jTFnome;
    private javax.swing.JTextField jTFnumero;
    private javax.swing.JTextField jTFrua;
    private javax.swing.JTextField jTFtelefone;
    private javax.swing.JTextField jTFuf;
    // End of variables declaration//GEN-END:variables
}
